### ISSUE TITLE
"pip install RPi.GPIO" fails

### ISSUE THREAD

**Issue by grf692** [inactivitytimeout/labists_pi_car#1]
Hej,

I tried to follow the guide for "Getting Started - Fresh Pi OS Install"
I installed fresh raspberry pi OS (64-bit) on a Pi3b+, it runs (upgraded) Debian 11 version fine. 

![image](https://github.com/inactivitytimeout/labists_pi_car/assets/30925906/3e5e31fd-02aa-486f-bf18-41cb0414d768)

However I am stuck at step 7 when doing "pip install RPi.GPIO"

![image](https://github.com/inactivitytimeout/labists_pi_car/assets/30925906/70cb2681-5dd7-4ccb-9a6b-60f00ca33ceb)

Any chance you can help me ?

**Comment by grf692** [comment]
Apparently fixed after installing python3-dev :)

**Comment by inactivitytimeout** [comment]
Great! This was a fun toy a couple of years ago. The software was incomplete, so I figured I would write some notes in case anyone else wanted a quick start.

**Comment by grf692** [comment]
My idea is to be able to connect remotely and use the camera to check on my dog when I am at work... Not sure where to start but at least the Jupyter Notebook is up and running and I can reach it via browser. Thanks for sharing the good notes!
